eleme/thriftpy

examples/calculator/calc_client.py
examples/calculator/calc_server.py
examples/oneway/sleep_client.py
examples/oneway/sleep_server.py
examples/pingpong/ping_client.py
examples/pingpong/ping_server.py
examples/tracker/stuffs.py
examples/tracker/tracker_client.py
examples/tracker/tracker_server.py
examples/tutorial/tutorial_client.py
examples/tutorial/tutorial_server.py
setup.py
tests/test_const.py
tests/test_container.py
tests/test_loader.py
tests/test_protocol_cybinary.py
tests/test_rpc.py
tests/test_tracker.py
thriftpy/__init__.py
thriftpy/_compat.py
thriftpy/protocol/__init__.py
thriftpy/thrift.py
thriftpy/trace/tracing.thrift
thriftpy/trace/tracker.py
thriftpy/transport/__init__.py

modified tracker

---

tests/test_tracker.py
thriftpy/trace/tracker.py

use method to get request_id

---

README.rst
docs/index.rst
tests/test_framed_transport.py
tests/test_protocol_cybinary.py
thriftpy/_compat.py
thriftpy/protocol/__init__.py
thriftpy/thrift.py
thriftpy/transport/__init__.py

make default since it's considered stable now

enable cython binary protocol by default

---

tests/test_tracking.py
thriftpy/contrib/tracking/__init__.py
thriftpy/contrib/tracking/tracker.py
thriftpy/contrib/tracking/tracking.thrift

changed seq

---

tests/test_tracking.py
thriftpy/contrib/tracking/tracker.py

should increase counter for every gen_header

---

tests/test_json_protocol.py
thriftpy/protocol/json.py

fix json protocol to fit the added requirement in thrift_spec, resolves #107

---

tests/test_tracking.py
thriftpy/contrib/tracking/__init__.py
thriftpy/contrib/tracking/tracking.thrift

make RequestInfo to be just a python object

---

tests/test_parser.py
thriftpy/parser/__init__.py
thriftpy/parser/parser.py

Enable multiple include dirs

---

tests/parser-cases/e_duplicate_field_id.thrift
tests/parser-cases/e_duplicate_field_name.thrift
tests/test_parser.py
thriftpy/parser/parser.py

Check duplicate field id or name

---

tests/test_socket.py
thriftpy/transport/socket.py

Fixes the exception of `error: [Errno 107] Transport endpoint is not connected`.
@lxyu @wooparadog

fix socket shutdown bug

---

tests/test_protocol_cybinary.py
thriftpy/protocol/cybin/endian_port.h

fix i16 byte swap bug on mac platforms

---

tests/test_protocol_cybinary.py
thriftpy/protocol/cybin/cybin.pyx

Allowed types:
list: all sequence types except string types
dict: all dict or dict like types
@lxyu @wooparadog

make subclasses of dict to pass the type check

---

thriftpy/protocol/cybin/cybin.pyx

add OverflowError to write_val decode exceptions

---

tests/test_parser.py
thriftpy/__init__.py
thriftpy/parser/__init__.py
thriftpy/parser/parser.py

@lxyu @maralla @amontalenti 
Ready now.

Add api load_fp to load thrift from file like object

---

thriftpy/parser/parser.py

@maralla  @lxyu Ref https://github.com/eleme/thriftpy/issues/144

Allow self-referencing recursive struct definition

---

tests/parser-cases/recursive_union.thrift
tests/test_parser.py
thriftpy/parser/parser.py

Fix recursive union parsing #157

---

thriftpy/server.py
thriftpy/tornado.py

use named loggers

---

tests/test_tracking.py
thriftpy/contrib/tracking/__init__.py
thriftpy/contrib/tracking/tracker.py
thriftpy/contrib/tracking/tracking.thrift

Add meta passing in header

---

tests/test_tracking.py
thriftpy/contrib/tracking/__init__.py
thriftpy/contrib/tracking/tracker.py
thriftpy/contrib/tracking/tracking.thrift

After some testing, there's actually no need for upgrading tracking version.

Add meta support during tracking process.

---

thriftpy/contrib/tracking/__init__.py
thriftpy/contrib/tracking/tracker.py
thriftpy/contrib/tracking/tracking.thrift

Add handshake logic when client lunchs the first request to server.

add handshake logic in tracker

---

tests/test_cytransport.py
thriftpy/transport/buffered/cybuffered.pyx
thriftpy/transport/cybase.pxd
thriftpy/transport/cybase.pyx
thriftpy/transport/framed/cyframed.pyx
thriftpy/transport/memory/cymemory.pyx

expose socket handle in cython transports

---

tests/parser-cases/issue_215.thrift
tests/test_parser.py
thriftpy/parser/lexer.py

Add word boundary for true/false literal lexing, close #215

---

README.rst
tests/test_http.py
thriftpy/http.py
thriftpy/thrift.py

It refers to original [THttpServer and THttpClient implement in thrift 0.9.3](https://github.com/apache/thrift/tree/0.9.3/lib/py/src). Hope you enjoy it.

Add THttpServer and THttpClient for simple http support in thriftpy.
